### PR TITLE
Using jupyter-panel-proxy

### PR DESCRIPTION
**Pull request by jsignell**
To test take a look at https://mybinder.org/v2/gh/pyviz-demos/glaciers/jsignell/jupyter-panel-server/?urlpath=panel/glaciers

### CODE REVIEW

**Comment by fmaussion** [comment]
Do I get this right that this is just using another way to serve the apps? I'll follow this closely, as we are "deploying" a number of new panel apps in the near future and are still looking for the best way to do so...

**Comment by jsignell** [comment]
Right. If you have this package installed in your env, then whenever you run `jupyter notebook` you will also get your panel app at `localhost:8888/panel` *as long as it is named main.ipynb*.

I'm still thinking about whether this is the right way to serve them generally.  I'd prefer to serve an index pointing to all of apps, but that seemed not to work. I will keep working on this locally and see how it goes.

**Comment by jsignell** [comment]
I just merged a fix to serve all notebooks in the dir. I plan to release jupyter-panel-proxy next week, then I'll merge this and open up some similar ones in other repos.

**Comment by jsignell** [comment]
@philippjfr - good with you if I merge?

**Comment by philippjfr** [comment]
Yes, go for it!

**Pull request merged**
